/**
 * @Package: TestObjectDefaults.cls
 * @Version: 1.0
 * @Author: Gunther Roskams
 * @Copyright: See MIT License
 * @Uses: TestFactory.cls
 *
 * -------------------------------------------------------------------
 * Description: Default definitions per object, to create (test) records.
 *
 * Created: 25/04/2020
 * Last Modified: 25/04/2020
 *
 * Unit tests:
 *
 * Changelog: 
 *
 */

public with sharing class TestObjectDefaults {

}